remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have onetheme: jekyll-theme-tactile
  - jemoji

kramdown:
  input: Kramdown

# Name of website
title:
description:

# Google Analytics
google_analytics: G-NBN6DDWEZP

author: Justin Townsend
linkedin_username: justin-j-townsend

defaults:
  - scope:
      path: "assets/samples"
    values:
      samplecode: true

collections:
  file-utilities:
    title: "File Management"
    output: true
    permalink: /file-utilities/:name
  pm-utilities:
    title: "Views on Project Management"
    output: true
    permalink: /pm-utilities/:name
# path-animations:
#    title: "Path Animations"
#    output: true
# Other
