remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have onetheme: jekyll-theme-tactile
- jemoji

# Name of website
title: 
description: 

# Google Analytics
google_analytics: G-NBN6DDWEZP

author:            Justin Townsend
linkedin_username: justin-j-townsend

defaults:
  - scope:
      path: "assets/samples"
    values:
      samplecode: true

collections: 
  pm-utilities:
   title: "Opinions on Project Management"
   output: true
   permalink: /pm-utilities/:name
  path-animations:
   title: "Path Animations"
   output: true
